<template>
  <section>
    <h3>SCSS variables</h3>
    <p>
      You may change prefixes, metrics (like sizes, spacings, breakpoints, etc),
      colors, specific HTML5 elements variables and much more, all only in
      <code>_variables.scss</code> file.
    </p>
    <p>
      Variables file are divided into different categories:
      <ul>
        <li>Colors</li>
        <li>Options</li>
        <li>Spacing</li>
        <li>Sizing</li>
        <li>Borders</li>
        <li>Shadows</li>
        <li>Breakpoints</li>
        <li>Grids</li>
        <li>Text</li>
        <li>Body</li>
        <li>Tables</li>
        <li>Navs</li>
        <li>Tooltips</li>
        <li>Inputs</li>
        <li>Progress</li>
      </ul>
    </p>

    <h4>Colors</h4>
    <div class="flow">
      <div class="cl-12 cl-md-6 pr-md-2">
        <p>Colors for the grayscale (white to black):</p>
        <table class="is-responsive">
          <thead>
            <tr>
              <th>Variable</th>
              <th>Value</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>$gray-00</td>
              <td>#fff</td>
            </tr>
            <tr>
              <td>$gray-10</td>
              <td>#f8f9fa</td>
            </tr>
            <tr>
              <td>$gray-20</td>
              <td>#e9ecef</td>
            </tr>
            <tr>
              <td>$gray-30</td>
              <td>#dee2e6</td>
            </tr>
            <tr>
              <td>$gray-40</td>
              <td>#ced4da</td>
            </tr>
            <tr>
              <td>$gray-50</td>
              <td>#adb5bd</td>
            </tr>
            <tr>
              <td>$gray-60</td>
              <td>#868e96</td>
            </tr>
            <tr>
              <td>$gray-70</td>
              <td>#495057</td>
            </tr>
            <tr>
              <td>$gray-80</td>
              <td>#343a40</td>
            </tr>
            <tr>
              <td>$gray-90</td>
              <td>#212529</td>
            </tr>
            <tr>
              <td>$gray-100</td>
              <td>#000</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="cl-12 cl-md-6 pl-md-2">
        <p>UI colors usable to backgrounds and text as utilities:</p>
        <table class="is-responsive">
          <thead>
            <tr>
              <th>Variable</th>
              <th>Value</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>$ui-blue</td>
              <td>#fff</td>
            </tr>
            <tr>
              <td>$ui-gray</td>
              <td>#f8f9fa</td>
            </tr>
            <tr>
              <td>$ui-red</td>
              <td>#e9ecef</td>
            </tr>
            <tr>
              <td>$ui-black</td>
              <td>#dee2e6</td>
            </tr>
            <tr>
              <td>$ui-green</td>
              <td>#ced4da</td>
            </tr>
            <tr>
              <td>$ui-brown</td>
              <td>#adb5bd</td>
            </tr>
            <tr>
              <td>$ui-orange</td>
              <td>#868e96</td>
            </tr>
            <tr>
              <td>$ui-purple</td>
              <td>#495057</td>
            </tr>
            <tr>
              <td>$ui-yellow</td>
              <td>#343a40</td>
            </tr>
            <tr>
              <td>$ui-pink</td>
              <td>#212529</td>
            </tr>
            <tr>
              <td>$ui-pink</td>
              <td>#000</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </section>
</template>
